### PR TITLE
Add Skycoin as dependency

### PR DESCRIPTION
**Pull request by Senyoret1**
This pr greatly simplifies the structure of the repository.

Previously, this repository was primarily composed of code copied from the Skycoin repository. Apparently it was done that way because the `github.com/skycoin/skycoin/src/util/logging` package of the Skycoin repo is incompatible with gopherjs, so it was necessary to manually modify the files and comment any line that used that package. This means that applying any change made in the Skycoin repo would require a lot of work.

This pr deletes all the code copied from the Skycoin repository and simply adds Skycoin as a vendored dependency using dep. To avoid compatibility problems with gopherjs, a file called `fix-skycoin-dependency.sh` was created, which replaces all the calls to the `github.com/skycoin/skycoin/src/util/logging` package with calls to the `log` package. The file can be executed by running `make fix-skycoin-dependency`. This means that it is now possible to apply changes made in the Skycoin repository simply by updating the dependencies with dep and then running `make fix-skycoin-dependency`, instead of having to modify code manually.

After making these changes, the library was recompiled with gopher and tested in the web wallet. Everything seems to continue to work as before.

The other changes are that `make format` was used in the files, to solve the formating problems; some comments were added in the code and `readme.md` was updated with information about how to compile with gopherjs, what to do after updating the dependencies, how to format Go files, etc. As always, the texts in readme.md could have writing errors.

### CODE REVIEW

**Comment by gz-c** [comment]
What is the problem with `github.com/skycoin/skycoin/src/util/logging`?

`github.com/skycoin/skycoin/src/util/logging` was changed entirely relatively recently, so the original decision may not have been related.

**Comment by gz-c** [comment]
It seems the logging dependency is pulling in a few other we don't want.  Can you try the `ignored` feature of `Gopkg.toml` (https://golang.github.io/dep/docs/Gopkg.toml.html)?

Hopefully this will let us exclude the logging dependency the dependencies it pulls in.

**Comment by gz-c** [comment]
I will look into removing the logging dependency in the meantime.  It may be fine to only use the `log` package in `coin` by default.  I would prefer the coin package to avoid extra dependencies.

**Comment by Senyoret1** [comment]
When using gopherjs without using `make fix-skycoin-dependency` before, the problem is this:
cmd1

If I use `ignored = ["github.com/skycoin/skycoin/src/util/logging"]` in `Gopkg.toml`, several dependencies are removed from the vendor folder, but the result when running gopherjs is the same. The problem seems to have to do with this:
cmd2

The search results indicate that only two files import `github.com/skycoin/skycoin/src/util/logging`, but in reality 5 files are using `logger` (in the packages `coin` and `cipher`), so the dependency tree appears a little complicated.

Also, if I use `ignored = ["github.com/skycoin/skycoin/src/util/logging"]` and use `make fix-skycoin-dependency` after updating the vendor folder, gopherjs does not throw any error, so it may be a good to use it in any case, but I would like to test the result a little more, to be sure everything works well at runtime.

**Comment by Senyoret1** [comment]
I tested with `ignored = ["github.com/skycoin/skycoin/src/util/logging"]` and could not find any problem, so I added a new commit with that change. it is still necessary to use `make fix-skycoin-dependency`, but at least the number of dependencies in the vendor folder is reduced.

**Pull request merged**
